# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy
---
policy:
  - template: [bug_report.yml]
    section:
      - id: [version]
        label:
          - name: V-4
            keys: [v4]
          - name: V-3
            keys: [v3]
          - name: V-2
            keys: [v2]
          - name: V-1
            keys: [v1]

      - id: [platform]
        label:
          - name: T-h5
            keys: [Web 端（H5）]

          - name: T-rn
            keys: [移动端（React-Native）]

          - name: T-harmony
            keys: [鸿蒙（Harmony）]

          - name: T-harmony_hybrid
            keys: [鸿蒙容器（Harmony Hybrid）]

          - name: T-quickapp
            keys: [快应用（QuickApp）]

          - name: T-weapp
            keys: [微信小程序]

          - name: T-jd
            keys: [京东小程序]

          - name: T-swan
            keys: [百度小程序]

          - name: T-alipay
            keys: [支付宝小程序]

          - name: T-tt
            keys: [抖音小程序]

          - name: T-qq
            keys: [QQ 小程序]

          - name: T-dd
            keys: [钉钉小程序]

          - name: T-qy
            keys: [企业微信小程序]

          - name: T-feishu
            keys: [飞书小程序]

          - name: T-kwai
            keys: [快手小程序]

      - id: [framework]
        label:
          - name: F-preact
            keys: [Preact]
          - name: F-react
            keys: [React]
          - name: F-solid
            keys: [Solid]
          - name: F-vue3
            keys: [Vue3]
          - name: F-vue2
            keys: [Vue2]
