export { createDocument, document } from './bom/document'
export { window } from './bom/window'
export { navigator } from './bom/navigator'
export { TaroEvent, createEvent } from './dom/event'
export { connectReactPage, createReactApp } from './dsl/react'
export { connectVuePage, createVueApp } from './dsl/vue'
export { createPageConfig, injectPageInstance, createComponentConfig } from './dsl/common'
export { Current } from './current'
export { TaroElement } from './dom/element'
export { TaroText } from './dom/text'
export { TaroNode } from './dom/node'
export { TaroRootElement } from './dom/root'
export { Style } from './dom/style'
export * from './dsl/hooks'
export { options } from './options'
