[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
napi = { version = "=2.14.0" }
napi-build = { version = "=2.1.0" }
napi-derive = { version = "=2.14.1" }
napi-sys = { version = "=2.3.0" }
once_cell = { version = "=1.18.0" }
tokio = { version = "=1.33.0" }
futures = { version = "=0.3.29" }
handlebars = { version = "=4.4.0" }
handlebars_misc_helpers = { version = "=0.13.0" }
serde_json = { version = "=1.0.108" }
serde = { version = "=1.0.192" }
anyhow = { version = "=1.0.75" }
console = { version = "=0.15.7" }

[profile.dev]
debug = 2
incremental = true

[profile.release]
codegen-units = 1
debug = false
lto = false # disabled by now, because it will significantly increase our compile time.
opt-level = 3
strip = true
