packages:
  - 'packages/**'
  - 'tests'
  - '!packages/taro-cli/templates/**'
  - '!**/__tests__/**'
  - '!**/dist/**'
  - 'npm/**'
  - 'crates/native_binding'

overrides:
  "@tarojs/helper>@babel/types": "^7.27.1"