packages:
  - 'packages/**'
  - 'tests'
  - '!packages/taro-cli/templates/**'
  - '!**/__tests__/**'
  - '!**/dist/**'
  - '!**/harmony_project/**'
  - 'npm/**'
  - 'crates/native_binding'
  - '../../a/taro/packages/taro-platform-ascf'