packages:
  - 'packages/**'
  - 'tt-dom-examples/**'
  - 'tests'
  - '!packages/taro-cli/templates/**'
  - '!**/__tests__/**'
  - '!**/dist/**'
  - '!**/harmony_project/**'
  - 'npm/**'
  - 'crates/native_binding'
