export const MODIFY_WEBPACK_CHAIN = 'modifyWebpackChain'
export const MODIFY_BUILD_ASSETS = 'modifyBuildAssets'
export const MODIFY_MINI_CONFIGS = 'modifyMiniConfigs'
export const ON_COMPILER_MAKE = 'onCompilerMake'
export const ON_BUILD_START = 'onBuildStart'
export const ON_BUILD_FINISH = 'onBuildFinish'
