name: 错误报告 🐞
description: >-
  创建一个新的错误报告。对于一般性问题，请在 GitHub Discussion 中发布。
title: "[Bug]: "
labels:
  - 待分类
  - bug
body:
  - type: input
    id: platform
    attributes:
      label: 相关平台
    validations:
      required: true
  - type: input
    id: library
    attributes:
      label: 小程序基础库版本
      description: 你可以在小程序开发者工具的「详情」中找到小程序基础库版本。
    validations:
      required: true
  - type: dropdown
    id: framework
    attributes:
      label: 使用框架
      options:
        - React
        - Preact
        - Vue 3
        - Vue 2
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 问题描述
    validations:
      required: true
  - type: input
    id: repro-link
    attributes:
      label: 复现链接
      description: 请提供一个 GitHub 或其它代码托管平台仓库的链接。
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: 复现步骤
      description: 请提供复现问题的步骤。
      placeholder: >-
        1. Go to above link
        2. Click on '....'
        3. ...
  - type: textarea
    id: system
    attributes:
      label: 环境信息
      description: 运行 `npx taro info` 并将输出粘贴在下面。
      render: bash
    validations:
      required: true
