import { processTypeEnum } from './constants';
export declare const isNodeModule: (filename: string) => boolean;
export declare function isNpmPkg(name: string): boolean;
export declare function isEmptyObject(obj: any): boolean;
export declare function isAliasPath(name: string, pathAlias?: object): boolean;
export declare function replaceAliasPath(filePath: string, name: string, pathAlias?: object): string;
export declare function promoteRelativePath(fPath: string): string;
export declare function resolveMainFilePath(p: string, extArrs?: string[]): string;
export declare const recursiveMerge: <T = any>(src: Partial<T>, ...args: (Partial<T> | undefined)[]) => any;
export declare function getInstalledNpmPkgPath(pkgName: string, basedir: string): string | null;
export declare function printLog(type: processTypeEnum, tag: string, filePath?: string): void;
export declare function removeHeadSlash(str: string): string;
export declare function readConfig(configPath: string): any;
