/* auto-generated by NAPI-RS */
/* eslint-disable */

export const enum CompilerType {
  Webpack4 = 'Webpack4',
  Webpack5 = 'Webpack5',
  Vite = 'Vite'
}

export interface CreateOptions {
  css: CSSType
  cssExt?: string
  framework: FrameworkType
  description?: string
  projectName: string
  version?: string
  date?: string
  typescript?: boolean
  template: string
  pageName: string
  compiler?: CompilerType
  setPageName?: string
  changeExt?: boolean
  isCustomTemplate?: boolean
}

export function createProject(conf: Project, handlers: Record<string, (err: Error | null, value: CreateOptions) => any>): Promise<void>

export const enum CSSType {
  None = 'None',
  Sass = 'Sass',
  Stylus = 'Stylus',
  Less = 'Less'
}

export const enum FrameworkType {
  React = 'React',
  Preact = 'Preact',
  Vue = 'Vue',
  Vue3 = 'Vue3'
}

export const enum NpmType {
  Yarn = 'Yarn',
  Cnpm = 'Cnpm',
  Pnpm = 'Pnpm',
  Npm = 'Npm'
}

export interface Project {
  name: string
  dir: string
  npm: NpmType
  description?: string
  typescript?: boolean
  template: string
  css: CSSType
  autoInstall?: boolean
  framework: FrameworkType
  templateRoot: string
  version: string
  date?: string
  compiler?: CompilerType
}

