/* eslint-disable simple-import-sort/exports */
export { Ad } from '@tarojs/components/lib/react'
export { AdCustom } from '@tarojs/components/lib/react'
export { AnimationVideo } from '@tarojs/components/lib/react'
export { AnimationView } from '@tarojs/components/lib/react'
export { ArCamera } from '@tarojs/components/lib/react'
export { Audio } from '@tarojs/components/lib/react'
export { AwemeData } from '@tarojs/components/lib/react'
export { Block } from '@tarojs/components/lib/react'
export { Button } from '@tarojs/components/lib/react'
export { Camera } from '@tarojs/components/lib/react'
export { Canvas } from '@tarojs/components/lib/react'
export { ChannelLive } from '@tarojs/components/lib/react'
export { ChannelVideo } from '@tarojs/components/lib/react'
export { Checkbox, CheckboxGroup } from '@tarojs/components/lib/react'
export { CommentDetail, CommentList } from '@tarojs/components/lib/react'
export { ContactButton } from '@tarojs/components/lib/react'
export { CoverImage } from '@tarojs/components/lib/react'
export { CoverView } from '@tarojs/components/lib/react'
export { CustomWrapper } from '@tarojs/components/lib/react'
export { Editor } from '@tarojs/components/lib/react'
export { FollowSwan } from '@tarojs/components/lib/react'
export { Form } from '@tarojs/components/lib/react'
export { FunctionalPageNavigator } from '@tarojs/components/lib/react'
export { Icon } from '@tarojs/components/lib/react'
// export { default as Image } from '@tarojs/components-react/dist/components/image'
export { default as Image } from './components/image'
export { InlinePaymentPanel } from '@tarojs/components/lib/react'
export { Input } from '@tarojs/components/lib/react'
export { KeyboardAccessory } from '@tarojs/components/lib/react'
// export { Label } from '@tarojs/components/lib/react'
export { Label } from './components/label/label'
export { Lifestyle } from '@tarojs/components/lib/react'
export { Like } from '@tarojs/components/lib/react'
export { LivePlayer } from '@tarojs/components/lib/react'
export { LivePusher } from '@tarojs/components/lib/react'
export { Login } from '@tarojs/components/lib/react'
export { Lottie } from '@tarojs/components/lib/react'
export { Map } from '@tarojs/components/lib/react'
export { MovableArea, MovableView } from '@tarojs/components/lib/react'
export { NavigationBar } from '@tarojs/components/lib/react'
export { Navigator } from '@tarojs/components/lib/react'
export { OfficialAccount } from '@tarojs/components/lib/react'
export { OpenData } from '@tarojs/components/lib/react'
export { PageMeta } from '@tarojs/components/lib/react'
export { Picker, PickerGroup } from '@tarojs/components/lib/react'
export { PickerView, PickerViewColumn } from '@tarojs/components/lib/react'
export { Progress } from '@tarojs/components/lib/react'
// export { default as PullDownRefresh } from '@tarojs/components-react/dist/components/pull-down-refresh'
export { default as PullDownRefresh } from './components/pull-down-refresh'
export { PullToRefresh } from '@tarojs/components/lib/react'
export { Radio, RadioGroup } from '@tarojs/components/lib/react'
export { RichText } from '@tarojs/components/lib/react'
export { RtcRoom, RtcRoomItem } from '@tarojs/components/lib/react'
// export { default as ScrollView } from '@tarojs/components-react/dist/components/scroll-view'
export { default as ScrollView } from './components/scroll-view'
export { ShareElement } from '@tarojs/components/lib/react'
export { Slider } from '@tarojs/components/lib/react'
export { NativeSlot, Slot } from '@tarojs/components/lib/react'
// export { Swiper, SwiperItem } from '@tarojs/components-react/dist/components/swiper'
export { Swiper, SwiperItem } from './components/swiper'
export { Switch } from '@tarojs/components/lib/react'
export { Tabbar, TabItem } from '@tarojs/components/lib/react'
export { Tabs } from '@tarojs/components/lib/react'
// export { default as Text } from '@tarojs/components-react/dist/components/text'
export { default as Text } from './components/text'
export { Textarea } from '@tarojs/components/lib/react'
export { Video, VideoControl, VideoDanmu } from '@tarojs/components/lib/react'
// export { default as View } from '@tarojs/components-react/dist/components/view'
export { default as View } from './components/view'
export { VoipRoom } from '@tarojs/components/lib/react'
export { WebView } from '@tarojs/components/lib/react'
export * from './components/block/block'
export * from './components/grid/grid'
export * from './components/list/list'
export * from './components/root-portal/root-portal'
export * from './components/sticky-header/sticky-header'
export * from './components/sticky-section/sticky-section'
// export * from './components/editor/editor'
export { MatchMedia } from './components/match-media/match-media'
export { default as PageContainer } from './components/page-container/page-container'
