import 'weui'
export { default as View } from './view'
export { default as Block } from './block'
export { default as Image } from './image'
export { default as Text } from './text'
export { default as Switch } from './switch'
export { default as Button } from './button'
export { default as Icon } from './icon'
export { default as Radio } from './radio'
export { default as Input } from './input'
export { default as ScrollView } from './scroll-view'
export { Swiper, SwiperItem } from './swiper/swiper'
export { default as Checkbox } from './checkbox'
export { default as Picker } from './picker'
export { default as Label } from './label'
export { default as Textarea } from './textarea'
export { default as Slider } from './slider'
export { default as Video } from './video'
export { default as Audio } from './audio'
export { default as Camera } from './camera'
export { default as Progress } from './progress'
export { default as RichText } from './rich-text'
export { default as Form } from './form'
export { default as RadioGroup } from './radio/radio-group'
export { default as CheckboxGroup } from './checkbox/checkbox-group'
export { default as Tabbar } from './tabbar'
export { default as TabbarContainer } from './tabbar/container'
export { default as TabbarPanel } from './tabbar/panel'
// export { default as Navigator } from './navigator'
