/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Type,
} from './components/icon/icon';
import {
  Mode,
} from './components/image/image';
import {
  Fields,
  Mode as Mode1,
} from './components/picker/picker';
import {
  Nodes,
} from './components/rich-text/rich-text';
import {
  Conf,
} from './components/tabbar/tabbar';
import {
  Danmu,
} from './components/video/video-danmu';

export namespace Components {
  interface TaroAudio {
    'autoplay': boolean;
    'controls': boolean;
    'loop': boolean;
    'muted': boolean;
    'src': string;
  }
  interface TaroBlock {}
  interface TaroButton {
    'disabled': boolean;
    'formType': 'submit' | 'reset' | null;
    'hoverClass': string;
    'hoverStartTime': number;
    'hoverStayTime': number;
    'loading': boolean;
    'plain': boolean;
    'size': string;
    'type': string;
  }
  interface TaroCamera {}
  interface TaroCanvas {
    'canvasId': string;
    'type': string;
  }
  interface TaroCheckbox {
    'checked': boolean;
    'color': string;
    'id': string;
    'name': string;
    'value': string;
  }
  interface TaroCheckboxGroup {
    'name': any;
  }
  interface TaroCoverImage {}
  interface TaroCoverView {}
  interface TaroForm {}
  interface TaroIcon {
    'color': string;
    'size': string | number;
    'type': Type;
  }
  interface TaroImage {
    'lazyLoad': boolean;
    'mode': Mode;
    'src': string;
  }
  interface TaroInputCore {
    'autoFocus': boolean;
    'confirmType': string;
    'disabled': boolean;
    'maxlength': number;
    'name': string;
    'password': boolean;
    'placeholder': string;
    'type': string;
    'value': string;
  }
  interface TaroLabel {
    'for': string;
  }
  interface TaroMoveableArea {}
  interface TaroMoveableView {}
  interface TaroNavigator {
    'delta': number;
    'hoverClass': string;
    'isHover': boolean;
    'openType': string;
    'url': string;
  }
  interface TaroOpenData {}
  interface TaroPickerCore {
    'disabled': boolean;
    'end': string;
    'fields': Fields;
    'mode': Mode;
    'name': string;
    'range': any[];
    'rangeKey': string;
    'start': string;
    'value': number | number[] | string;
  }
  interface TaroPickerGroup {
    'columnId': string;
    'height': number;
    'mode': 'time' | 'date';
    'onColumnChange': (height: number, columnId: string) => void;
    'range': any[];
    'rangeKey': string;
    'updateDay': (value: number, fields: number) => void;
    'updateHeight': (height: number, columnId: string, needRevise?: boolean) => void;
  }
  interface TaroPickerView {}
  interface TaroPickerViewColumn {}
  interface TaroProgress {
    'active': boolean;
    'activeColor': string;
    'backgroundColor': string;
    'borderRadius': number | string;
    'fontSize': number | string;
    'percent': number;
    'showInfo': boolean;
    'strokeWidth': number | string;
  }
  interface TaroPullToRefresh {
    'damping': number;
    'distanceToRefresh': number;
    'indicator': { activate: string; deactivate: string; release: string; finish: string; };
    'prefixCls': string;
    'refreshing': string;
  }
  interface TaroRadio {
    'checked': boolean;
    'id': string;
    'name': string;
    'value': string;
  }
  interface TaroRadioGroup {
    'name': any;
  }
  interface TaroRichText {
    'nodes': Nodes;
  }
  interface TaroScrollView {
    'lowerThreshold': number | string;
    'mpScrollIntoView': string;
    'mpScrollLeft': number | string;
    'mpScrollTop': number | string;
    'scrollWithAnimation': boolean;
    'scrollX': boolean;
    'scrollY': boolean;
    'upperThreshold': number | string;
  }
  interface TaroSlider {
    'activeColor': string;
    'backgroundColor': string;
    'blockColor': string;
    'blockSize': number;
    'disabled': boolean;
    'max': number;
    'min': number;
    'name': string;
    'showValue': boolean;
    'step': number;
    'value': number | null;
  }
  interface TaroSwiper {
    /**
    * 是否自动切换
    */
    'autoplay': boolean;
    /**
    * 是否采用衔接滑动
    */
    'circular': boolean;
    /**
    * 当前所在滑块的 index
    */
    'current': number;
    /**
    * 同时显示的滑块数量
    */
    'displayMultipleItems': number;
    /**
    * 滑动动画时长
    */
    'duration': number;
    /**
    * 当前选中的指示点颜色
    */
    'indicatorActiveColor': string;
    /**
    * 指示点颜色
    */
    'indicatorColor': string;
    /**
    * 是否显示面板指示点
    */
    'indicatorDots': boolean;
    /**
    * 自动切换时间间隔
    */
    'interval': number;
    /**
    * 前边距，可用于露出前一项的一小部分，接受 px 值
    */
    'previousMargin': string;
    /**
    * 滑动方向是否为纵向
    */
    'vertical': boolean;
  }
  interface TaroSwiperItem {
    'itemId': string;
  }
  interface TaroSwitch {
    'checked': boolean;
    'color': string;
    'name': string;
    'type': string;
  }
  interface TaroTabbar {
    'conf': Conf;
  }
  interface TaroText {
    'selectable': boolean;
  }
  interface TaroTextarea {
    'autoFocus': boolean;
    'disabled': boolean;
    'maxlength': number;
    'name': string;
    'placeholder': string;
    'value': string;
  }
  interface TaroVideo {
    /**
    * 是否自动播放
    */
    'autoplay': boolean;
    /**
    * 是否显示默认播放控件（播放/暂停按钮、播放进度、时间）
    */
    'controls': boolean;
    /**
    * 是否显示弹幕按钮
    */
    'danmuBtn': boolean;
    /**
    * 弹幕列表
    */
    'danmuList': [];
    /**
    * 指定视频时长
    */
    'duration': number;
    /**
    * 是否展示弹幕
    */
    'enableDanmu': boolean;
    /**
    * 是否开启播放手势，即双击切换播放/暂停
    */
    'enablePlayGesture': boolean;
    /**
    * 是否开启控制进度的手势
    */
    'enableProgressGesture': boolean;
    /**
    * 指定视频初始播放位置
    */
    'initialTime': number;
    /**
    * 是否循环播放
    */
    'loop': boolean;
    /**
    * 是否静音播放
    */
    'muted': boolean;
    /**
    * 当视频大小与 video 容器大小不一致时，视频的表现形式
    */
    'objectFit': 'contain' | 'fill' | 'cover';
    /**
    * 视频封面的图片网络资源地址或云文件ID（2.3.0）。若 controls 属性值为 false 则设置 poster 无效
    */
    'poster': string;
    /**
    * 是否显示视频中间的播放按钮
    */
    'showCenterPlayBtn': boolean;
    /**
    * 是否显示全屏按钮
    */
    'showFullscreenBtn': boolean;
    /**
    * 是否显示静音按钮
    */
    'showMuteBtn': boolean;
    /**
    * 是否显示视频底部控制栏的播放按钮
    */
    'showPlayBtn': boolean;
    'showProgress': boolean;
    /**
    * 要播放视频的资源地址
    */
    'src': string;
    /**
    * 在非全屏模式下，是否开启亮度与音量调节手势
    */
    'vslideGesture': boolean;
    /**
    * 在全屏模式下，是否开启亮度与音量调节手势
    */
    'vslideGestureInFullscreen': boolean;
  }
  interface TaroVideoControl {
    'controls': boolean;
    'currentTime': number;
    'duration': number;
    'getIsDraggingProgressBall': () => Promise<boolean>;
    'isPlaying': boolean;
    'pauseFunc': () => void;
    'playFunc': () => void;
    'seekFunc': (position: number) => void;
    'setCurrentTime': (time: number) => Promise<void>;
    'setProgressBall': (percentage: number) => Promise<void>;
    'showPlayBtn': boolean;
    'showProgress': boolean;
    'toggleVisibility': (nextVisible?: boolean | undefined) => Promise<void>;
  }
  interface TaroVideoDanmu {
    'enable': boolean;
    'sendDanmu': (danmuList?: Partial<Danmu> | Partial<Danmu>[]) => Promise<void>;
    'tick': (currentTime: number) => Promise<void>;
  }
  interface TaroView {
    'hoverClass': string;
    'hoverStartTime': number;
    'hoverStayTime': number;
  }
  interface TaroWebView {
    'src': string;
  }
}

declare global {


  interface HTMLTaroAudioElement extends Components.TaroAudio, HTMLStencilElement {}
  var HTMLTaroAudioElement: {
    prototype: HTMLTaroAudioElement;
    new (): HTMLTaroAudioElement;
  };

  interface HTMLTaroBlockElement extends Components.TaroBlock, HTMLStencilElement {}
  var HTMLTaroBlockElement: {
    prototype: HTMLTaroBlockElement;
    new (): HTMLTaroBlockElement;
  };

  interface HTMLTaroButtonElement extends Components.TaroButton, HTMLStencilElement {}
  var HTMLTaroButtonElement: {
    prototype: HTMLTaroButtonElement;
    new (): HTMLTaroButtonElement;
  };

  interface HTMLTaroCameraElement extends Components.TaroCamera, HTMLStencilElement {}
  var HTMLTaroCameraElement: {
    prototype: HTMLTaroCameraElement;
    new (): HTMLTaroCameraElement;
  };

  interface HTMLTaroCanvasElement extends Components.TaroCanvas, HTMLStencilElement {}
  var HTMLTaroCanvasElement: {
    prototype: HTMLTaroCanvasElement;
    new (): HTMLTaroCanvasElement;
  };

  interface HTMLTaroCheckboxElement extends Components.TaroCheckbox, HTMLStencilElement {}
  var HTMLTaroCheckboxElement: {
    prototype: HTMLTaroCheckboxElement;
    new (): HTMLTaroCheckboxElement;
  };

  interface HTMLTaroCheckboxGroupElement extends Components.TaroCheckboxGroup, HTMLStencilElement {}
  var HTMLTaroCheckboxGroupElement: {
    prototype: HTMLTaroCheckboxGroupElement;
    new (): HTMLTaroCheckboxGroupElement;
  };

  interface HTMLTaroCoverImageElement extends Components.TaroCoverImage, HTMLStencilElement {}
  var HTMLTaroCoverImageElement: {
    prototype: HTMLTaroCoverImageElement;
    new (): HTMLTaroCoverImageElement;
  };

  interface HTMLTaroCoverViewElement extends Components.TaroCoverView, HTMLStencilElement {}
  var HTMLTaroCoverViewElement: {
    prototype: HTMLTaroCoverViewElement;
    new (): HTMLTaroCoverViewElement;
  };

  interface HTMLTaroFormElement extends Components.TaroForm, HTMLStencilElement {}
  var HTMLTaroFormElement: {
    prototype: HTMLTaroFormElement;
    new (): HTMLTaroFormElement;
  };

  interface HTMLTaroIconElement extends Components.TaroIcon, HTMLStencilElement {}
  var HTMLTaroIconElement: {
    prototype: HTMLTaroIconElement;
    new (): HTMLTaroIconElement;
  };

  interface HTMLTaroImageElement extends Components.TaroImage, HTMLStencilElement {}
  var HTMLTaroImageElement: {
    prototype: HTMLTaroImageElement;
    new (): HTMLTaroImageElement;
  };

  interface HTMLTaroInputCoreElement extends Components.TaroInputCore, HTMLStencilElement {}
  var HTMLTaroInputCoreElement: {
    prototype: HTMLTaroInputCoreElement;
    new (): HTMLTaroInputCoreElement;
  };

  interface HTMLTaroLabelElement extends Components.TaroLabel, HTMLStencilElement {}
  var HTMLTaroLabelElement: {
    prototype: HTMLTaroLabelElement;
    new (): HTMLTaroLabelElement;
  };

  interface HTMLTaroMoveableAreaElement extends Components.TaroMoveableArea, HTMLStencilElement {}
  var HTMLTaroMoveableAreaElement: {
    prototype: HTMLTaroMoveableAreaElement;
    new (): HTMLTaroMoveableAreaElement;
  };

  interface HTMLTaroMoveableViewElement extends Components.TaroMoveableView, HTMLStencilElement {}
  var HTMLTaroMoveableViewElement: {
    prototype: HTMLTaroMoveableViewElement;
    new (): HTMLTaroMoveableViewElement;
  };

  interface HTMLTaroNavigatorElement extends Components.TaroNavigator, HTMLStencilElement {}
  var HTMLTaroNavigatorElement: {
    prototype: HTMLTaroNavigatorElement;
    new (): HTMLTaroNavigatorElement;
  };

  interface HTMLTaroOpenDataElement extends Components.TaroOpenData, HTMLStencilElement {}
  var HTMLTaroOpenDataElement: {
    prototype: HTMLTaroOpenDataElement;
    new (): HTMLTaroOpenDataElement;
  };

  interface HTMLTaroPickerCoreElement extends Components.TaroPickerCore, HTMLStencilElement {}
  var HTMLTaroPickerCoreElement: {
    prototype: HTMLTaroPickerCoreElement;
    new (): HTMLTaroPickerCoreElement;
  };

  interface HTMLTaroPickerGroupElement extends Components.TaroPickerGroup, HTMLStencilElement {}
  var HTMLTaroPickerGroupElement: {
    prototype: HTMLTaroPickerGroupElement;
    new (): HTMLTaroPickerGroupElement;
  };

  interface HTMLTaroPickerViewElement extends Components.TaroPickerView, HTMLStencilElement {}
  var HTMLTaroPickerViewElement: {
    prototype: HTMLTaroPickerViewElement;
    new (): HTMLTaroPickerViewElement;
  };

  interface HTMLTaroPickerViewColumnElement extends Components.TaroPickerViewColumn, HTMLStencilElement {}
  var HTMLTaroPickerViewColumnElement: {
    prototype: HTMLTaroPickerViewColumnElement;
    new (): HTMLTaroPickerViewColumnElement;
  };

  interface HTMLTaroProgressElement extends Components.TaroProgress, HTMLStencilElement {}
  var HTMLTaroProgressElement: {
    prototype: HTMLTaroProgressElement;
    new (): HTMLTaroProgressElement;
  };

  interface HTMLTaroPullToRefreshElement extends Components.TaroPullToRefresh, HTMLStencilElement {}
  var HTMLTaroPullToRefreshElement: {
    prototype: HTMLTaroPullToRefreshElement;
    new (): HTMLTaroPullToRefreshElement;
  };

  interface HTMLTaroRadioElement extends Components.TaroRadio, HTMLStencilElement {}
  var HTMLTaroRadioElement: {
    prototype: HTMLTaroRadioElement;
    new (): HTMLTaroRadioElement;
  };

  interface HTMLTaroRadioGroupElement extends Components.TaroRadioGroup, HTMLStencilElement {}
  var HTMLTaroRadioGroupElement: {
    prototype: HTMLTaroRadioGroupElement;
    new (): HTMLTaroRadioGroupElement;
  };

  interface HTMLTaroRichTextElement extends Components.TaroRichText, HTMLStencilElement {}
  var HTMLTaroRichTextElement: {
    prototype: HTMLTaroRichTextElement;
    new (): HTMLTaroRichTextElement;
  };

  interface HTMLTaroScrollViewElement extends Components.TaroScrollView, HTMLStencilElement {}
  var HTMLTaroScrollViewElement: {
    prototype: HTMLTaroScrollViewElement;
    new (): HTMLTaroScrollViewElement;
  };

  interface HTMLTaroSliderElement extends Components.TaroSlider, HTMLStencilElement {}
  var HTMLTaroSliderElement: {
    prototype: HTMLTaroSliderElement;
    new (): HTMLTaroSliderElement;
  };

  interface HTMLTaroSwiperElement extends Components.TaroSwiper, HTMLStencilElement {}
  var HTMLTaroSwiperElement: {
    prototype: HTMLTaroSwiperElement;
    new (): HTMLTaroSwiperElement;
  };

  interface HTMLTaroSwiperItemElement extends Components.TaroSwiperItem, HTMLStencilElement {}
  var HTMLTaroSwiperItemElement: {
    prototype: HTMLTaroSwiperItemElement;
    new (): HTMLTaroSwiperItemElement;
  };

  interface HTMLTaroSwitchElement extends Components.TaroSwitch, HTMLStencilElement {}
  var HTMLTaroSwitchElement: {
    prototype: HTMLTaroSwitchElement;
    new (): HTMLTaroSwitchElement;
  };

  interface HTMLTaroTabbarElement extends Components.TaroTabbar, HTMLStencilElement {}
  var HTMLTaroTabbarElement: {
    prototype: HTMLTaroTabbarElement;
    new (): HTMLTaroTabbarElement;
  };

  interface HTMLTaroTextElement extends Components.TaroText, HTMLStencilElement {}
  var HTMLTaroTextElement: {
    prototype: HTMLTaroTextElement;
    new (): HTMLTaroTextElement;
  };

  interface HTMLTaroTextareaElement extends Components.TaroTextarea, HTMLStencilElement {}
  var HTMLTaroTextareaElement: {
    prototype: HTMLTaroTextareaElement;
    new (): HTMLTaroTextareaElement;
  };

  interface HTMLTaroVideoElement extends Components.TaroVideo, HTMLStencilElement {}
  var HTMLTaroVideoElement: {
    prototype: HTMLTaroVideoElement;
    new (): HTMLTaroVideoElement;
  };

  interface HTMLTaroVideoControlElement extends Components.TaroVideoControl, HTMLStencilElement {}
  var HTMLTaroVideoControlElement: {
    prototype: HTMLTaroVideoControlElement;
    new (): HTMLTaroVideoControlElement;
  };

  interface HTMLTaroVideoDanmuElement extends Components.TaroVideoDanmu, HTMLStencilElement {}
  var HTMLTaroVideoDanmuElement: {
    prototype: HTMLTaroVideoDanmuElement;
    new (): HTMLTaroVideoDanmuElement;
  };

  interface HTMLTaroViewElement extends Components.TaroView, HTMLStencilElement {}
  var HTMLTaroViewElement: {
    prototype: HTMLTaroViewElement;
    new (): HTMLTaroViewElement;
  };

  interface HTMLTaroWebViewElement extends Components.TaroWebView, HTMLStencilElement {}
  var HTMLTaroWebViewElement: {
    prototype: HTMLTaroWebViewElement;
    new (): HTMLTaroWebViewElement;
  };
  interface HTMLElementTagNameMap {
    'taro-audio': HTMLTaroAudioElement;
    'taro-block': HTMLTaroBlockElement;
    'taro-button': HTMLTaroButtonElement;
    'taro-camera': HTMLTaroCameraElement;
    'taro-canvas': HTMLTaroCanvasElement;
    'taro-checkbox': HTMLTaroCheckboxElement;
    'taro-checkbox-group': HTMLTaroCheckboxGroupElement;
    'taro-cover-image': HTMLTaroCoverImageElement;
    'taro-cover-view': HTMLTaroCoverViewElement;
    'taro-form': HTMLTaroFormElement;
    'taro-icon': HTMLTaroIconElement;
    'taro-image': HTMLTaroImageElement;
    'taro-input-core': HTMLTaroInputCoreElement;
    'taro-label': HTMLTaroLabelElement;
    'taro-moveable-area': HTMLTaroMoveableAreaElement;
    'taro-moveable-view': HTMLTaroMoveableViewElement;
    'taro-navigator': HTMLTaroNavigatorElement;
    'taro-open-data': HTMLTaroOpenDataElement;
    'taro-picker-core': HTMLTaroPickerCoreElement;
    'taro-picker-group': HTMLTaroPickerGroupElement;
    'taro-picker-view': HTMLTaroPickerViewElement;
    'taro-picker-view-column': HTMLTaroPickerViewColumnElement;
    'taro-progress': HTMLTaroProgressElement;
    'taro-pull-to-refresh': HTMLTaroPullToRefreshElement;
    'taro-radio': HTMLTaroRadioElement;
    'taro-radio-group': HTMLTaroRadioGroupElement;
    'taro-rich-text': HTMLTaroRichTextElement;
    'taro-scroll-view': HTMLTaroScrollViewElement;
    'taro-slider': HTMLTaroSliderElement;
    'taro-swiper': HTMLTaroSwiperElement;
    'taro-swiper-item': HTMLTaroSwiperItemElement;
    'taro-switch': HTMLTaroSwitchElement;
    'taro-tabbar': HTMLTaroTabbarElement;
    'taro-text': HTMLTaroTextElement;
    'taro-textarea': HTMLTaroTextareaElement;
    'taro-video': HTMLTaroVideoElement;
    'taro-video-control': HTMLTaroVideoControlElement;
    'taro-video-danmu': HTMLTaroVideoDanmuElement;
    'taro-view': HTMLTaroViewElement;
    'taro-web-view': HTMLTaroWebViewElement;
  }
}

declare namespace LocalJSX {
  interface TaroAudio {
    'autoplay'?: boolean;
    'controls'?: boolean;
    'loop'?: boolean;
    'muted'?: boolean;
    'onEnded'?: (event: CustomEvent<any>) => void;
    'onError'?: (event: CustomEvent<any>) => void;
    'onPause'?: (event: CustomEvent<any>) => void;
    'onPlay'?: (event: CustomEvent<any>) => void;
    'onTimeupdate'?: (event: CustomEvent<any>) => void;
    'src'?: string;
  }
  interface TaroBlock {}
  interface TaroButton {
    'disabled'?: boolean;
    'formType'?: 'submit' | 'reset' | null;
    'hoverClass'?: string;
    'hoverStartTime'?: number;
    'hoverStayTime'?: number;
    'loading'?: boolean;
    'onTarobuttonreset'?: (event: CustomEvent<any>) => void;
    'onTarobuttonsubmit'?: (event: CustomEvent<any>) => void;
    'plain'?: boolean;
    'size'?: string;
    'type'?: string;
  }
  interface TaroCamera {}
  interface TaroCanvas {
    'canvasId'?: string;
    'onLongtap'?: (event: CustomEvent<any>) => void;
    'type'?: string;
  }
  interface TaroCheckbox {
    'checked'?: boolean;
    'color'?: string;
    'id'?: string;
    'name'?: string;
    'onCheckboxchange'?: (event: CustomEvent<any>) => void;
    'value'?: string;
  }
  interface TaroCheckboxGroup {
    'name'?: any;
    'onChange'?: (event: CustomEvent<any>) => void;
  }
  interface TaroCoverImage {}
  interface TaroCoverView {}
  interface TaroForm {
    'onSubmit'?: (event: CustomEvent<any>) => void;
  }
  interface TaroIcon {
    'color'?: string;
    'size'?: string | number;
    'type'?: Type;
  }
  interface TaroImage {
    'lazyLoad'?: boolean;
    'mode'?: Mode;
    'onError'?: (event: CustomEvent<any>) => void;
    'onLoad'?: (event: CustomEvent<any>) => void;
    'src'?: string;
  }
  interface TaroInputCore {
    'autoFocus'?: boolean;
    'confirmType'?: string;
    'disabled'?: boolean;
    'maxlength'?: number;
    'name'?: string;
    'onBlur'?: (event: CustomEvent<any>) => void;
    'onChange'?: (event: CustomEvent<any>) => void;
    'onConfirm'?: (event: CustomEvent<any>) => void;
    'onFocus'?: (event: CustomEvent<any>) => void;
    'onInput'?: (event: CustomEvent<any>) => void;
    'onKeydown'?: (event: CustomEvent<any>) => void;
    'password'?: boolean;
    'placeholder'?: string;
    'type'?: string;
    'value'?: string;
  }
  interface TaroLabel {
    'for'?: string;
  }
  interface TaroMoveableArea {}
  interface TaroMoveableView {}
  interface TaroNavigator {
    'delta'?: number;
    'hoverClass'?: string;
    'isHover'?: boolean;
    'onComplete'?: (event: CustomEvent<any>) => void;
    'onCuccess'?: (event: CustomEvent<any>) => void;
    'onFail'?: (event: CustomEvent<any>) => void;
    'openType'?: string;
    'url'?: string;
  }
  interface TaroOpenData {}
  interface TaroPickerCore {
    'disabled'?: boolean;
    'end'?: string;
    'fields'?: Fields;
    'mode'?: Mode;
    'name'?: string;
    'onCancel'?: (event: CustomEvent<any>) => void;
    'onChange'?: (event: CustomEvent<any>) => void;
    'onColumnchange'?: (event: CustomEvent<any>) => void;
    'range'?: any[];
    'rangeKey'?: string;
    'start'?: string;
    'value'?: number | number[] | string;
  }
  interface TaroPickerGroup {
    'columnId'?: string;
    'height'?: number;
    'mode'?: 'time' | 'date';
    'onColumnChange'?: (height: number, columnId: string) => void;
    'range'?: any[];
    'rangeKey'?: string;
    'updateDay'?: (value: number, fields: number) => void;
    'updateHeight'?: (height: number, columnId: string, needRevise?: boolean) => void;
  }
  interface TaroPickerView {}
  interface TaroPickerViewColumn {}
  interface TaroProgress {
    'active'?: boolean;
    'activeColor'?: string;
    'backgroundColor'?: string;
    'borderRadius'?: number | string;
    'fontSize'?: number | string;
    'percent'?: number;
    'showInfo'?: boolean;
    'strokeWidth'?: number | string;
  }
  interface TaroPullToRefresh {
    'damping'?: number;
    'distanceToRefresh'?: number;
    'indicator'?: { activate: string; deactivate: string; release: string; finish: string; };
    'onRefresh'?: (event: CustomEvent<any>) => void;
    'prefixCls'?: string;
    'refreshing'?: string;
  }
  interface TaroRadio {
    'checked'?: boolean;
    'id'?: string;
    'name'?: string;
    'onRadiochange'?: (event: CustomEvent<any>) => void;
    'value'?: string;
  }
  interface TaroRadioGroup {
    'name'?: any;
    'onChange'?: (event: CustomEvent<any>) => void;
  }
  interface TaroRichText {
    'nodes'?: Nodes;
  }
  interface TaroScrollView {
    'lowerThreshold'?: number | string;
    'mpScrollIntoView'?: string;
    'mpScrollLeft'?: number | string;
    'mpScrollTop'?: number | string;
    'onScroll'?: (event: CustomEvent<any>) => void;
    'onScrolltolower'?: (event: CustomEvent<any>) => void;
    'onScrolltoupper'?: (event: CustomEvent<any>) => void;
    'scrollWithAnimation'?: boolean;
    'scrollX'?: boolean;
    'scrollY'?: boolean;
    'upperThreshold'?: number | string;
  }
  interface TaroSlider {
    'activeColor'?: string;
    'backgroundColor'?: string;
    'blockColor'?: string;
    'blockSize'?: number;
    'disabled'?: boolean;
    'max'?: number;
    'min'?: number;
    'name'?: string;
    'onChange'?: (event: CustomEvent<any>) => void;
    'onChanging'?: (event: CustomEvent<any>) => void;
    'showValue'?: boolean;
    'step'?: number;
    'value'?: number | null;
  }
  interface TaroSwiper {
    /**
    * 是否自动切换
    */
    'autoplay'?: boolean;
    /**
    * 是否采用衔接滑动
    */
    'circular'?: boolean;
    /**
    * 当前所在滑块的 index
    */
    'current'?: number;
    /**
    * 同时显示的滑块数量
    */
    'displayMultipleItems'?: number;
    /**
    * 滑动动画时长
    */
    'duration'?: number;
    /**
    * 当前选中的指示点颜色
    */
    'indicatorActiveColor'?: string;
    /**
    * 指示点颜色
    */
    'indicatorColor'?: string;
    /**
    * 是否显示面板指示点
    */
    'indicatorDots'?: boolean;
    /**
    * 自动切换时间间隔
    */
    'interval'?: number;
    'onAnimationfinish'?: (event: CustomEvent<any>) => void;
    'onChange'?: (event: CustomEvent<any>) => void;
    /**
    * 前边距，可用于露出前一项的一小部分，接受 px 值
    */
    'previousMargin'?: string;
    /**
    * 滑动方向是否为纵向
    */
    'vertical'?: boolean;
  }
  interface TaroSwiperItem {
    'itemId'?: string;
  }
  interface TaroSwitch {
    'checked'?: boolean;
    'color'?: string;
    'name'?: string;
    'onChange'?: (event: CustomEvent<any>) => void;
    'type'?: string;
  }
  interface TaroTabbar {
    'conf'?: Conf;
    'onLongpress'?: (event: CustomEvent<any>) => void;
  }
  interface TaroText {
    'selectable'?: boolean;
  }
  interface TaroTextarea {
    'autoFocus'?: boolean;
    'disabled'?: boolean;
    'maxlength'?: number;
    'name'?: string;
    'onBlur'?: (event: CustomEvent<any>) => void;
    'onChange'?: (event: CustomEvent<any>) => void;
    'onFocus'?: (event: CustomEvent<any>) => void;
    'onInput'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
    'value'?: string;
  }
  interface TaroVideo {
    /**
    * 是否自动播放
    */
    'autoplay'?: boolean;
    /**
    * 是否显示默认播放控件（播放/暂停按钮、播放进度、时间）
    */
    'controls'?: boolean;
    /**
    * 是否显示弹幕按钮
    */
    'danmuBtn'?: boolean;
    /**
    * 弹幕列表
    */
    'danmuList'?: [];
    /**
    * 指定视频时长
    */
    'duration'?: number;
    /**
    * 是否展示弹幕
    */
    'enableDanmu'?: boolean;
    /**
    * 是否开启播放手势，即双击切换播放/暂停
    */
    'enablePlayGesture'?: boolean;
    /**
    * 是否开启控制进度的手势
    */
    'enableProgressGesture'?: boolean;
    /**
    * 指定视频初始播放位置
    */
    'initialTime'?: number;
    /**
    * 是否循环播放
    */
    'loop'?: boolean;
    /**
    * 是否静音播放
    */
    'muted'?: boolean;
    /**
    * 当视频大小与 video 容器大小不一致时，视频的表现形式
    */
    'objectFit'?: 'contain' | 'fill' | 'cover';
    'onEnded'?: (event: CustomEvent<any>) => void;
    'onError'?: (event: CustomEvent<any>) => void;
    'onFullscreenchange'?: (event: CustomEvent<any>) => void;
    'onLoadedmetadata'?: (event: CustomEvent<any>) => void;
    'onPause'?: (event: CustomEvent<any>) => void;
    'onPlay'?: (event: CustomEvent<any>) => void;
    'onProgress'?: (event: CustomEvent<any>) => void;
    'onTimeupdate'?: (event: CustomEvent<any>) => void;
    /**
    * 视频封面的图片网络资源地址或云文件ID（2.3.0）。若 controls 属性值为 false 则设置 poster 无效
    */
    'poster'?: string;
    /**
    * 是否显示视频中间的播放按钮
    */
    'showCenterPlayBtn'?: boolean;
    /**
    * 是否显示全屏按钮
    */
    'showFullscreenBtn'?: boolean;
    /**
    * 是否显示静音按钮
    */
    'showMuteBtn'?: boolean;
    /**
    * 是否显示视频底部控制栏的播放按钮
    */
    'showPlayBtn'?: boolean;
    'showProgress'?: boolean;
    /**
    * 要播放视频的资源地址
    */
    'src'?: string;
    /**
    * 在非全屏模式下，是否开启亮度与音量调节手势
    */
    'vslideGesture'?: boolean;
    /**
    * 在全屏模式下，是否开启亮度与音量调节手势
    */
    'vslideGestureInFullscreen'?: boolean;
  }
  interface TaroVideoControl {
    'controls'?: boolean;
    'currentTime'?: number;
    'duration'?: number;
    'isPlaying'?: boolean;
    'pauseFunc'?: () => void;
    'playFunc'?: () => void;
    'seekFunc'?: (position: number) => void;
    'showPlayBtn'?: boolean;
    'showProgress'?: boolean;
  }
  interface TaroVideoDanmu {
    'enable'?: boolean;
  }
  interface TaroView {
    'hoverClass'?: string;
    'hoverStartTime'?: number;
    'hoverStayTime'?: number;
    'onLongpress'?: (event: CustomEvent<any>) => void;
  }
  interface TaroWebView {
    'onError'?: (event: CustomEvent<any>) => void;
    'onLoad'?: (event: CustomEvent<any>) => void;
    'src'?: string;
  }

  interface IntrinsicElements {
    'taro-audio': TaroAudio;
    'taro-block': TaroBlock;
    'taro-button': TaroButton;
    'taro-camera': TaroCamera;
    'taro-canvas': TaroCanvas;
    'taro-checkbox': TaroCheckbox;
    'taro-checkbox-group': TaroCheckboxGroup;
    'taro-cover-image': TaroCoverImage;
    'taro-cover-view': TaroCoverView;
    'taro-form': TaroForm;
    'taro-icon': TaroIcon;
    'taro-image': TaroImage;
    'taro-input-core': TaroInputCore;
    'taro-label': TaroLabel;
    'taro-moveable-area': TaroMoveableArea;
    'taro-moveable-view': TaroMoveableView;
    'taro-navigator': TaroNavigator;
    'taro-open-data': TaroOpenData;
    'taro-picker-core': TaroPickerCore;
    'taro-picker-group': TaroPickerGroup;
    'taro-picker-view': TaroPickerView;
    'taro-picker-view-column': TaroPickerViewColumn;
    'taro-progress': TaroProgress;
    'taro-pull-to-refresh': TaroPullToRefresh;
    'taro-radio': TaroRadio;
    'taro-radio-group': TaroRadioGroup;
    'taro-rich-text': TaroRichText;
    'taro-scroll-view': TaroScrollView;
    'taro-slider': TaroSlider;
    'taro-swiper': TaroSwiper;
    'taro-swiper-item': TaroSwiperItem;
    'taro-switch': TaroSwitch;
    'taro-tabbar': TaroTabbar;
    'taro-text': TaroText;
    'taro-textarea': TaroTextarea;
    'taro-video': TaroVideo;
    'taro-video-control': TaroVideoControl;
    'taro-video-danmu': TaroVideoDanmu;
    'taro-view': TaroView;
    'taro-web-view': TaroWebView;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'taro-audio': LocalJSX.TaroAudio & JSXBase.HTMLAttributes<HTMLTaroAudioElement>;
      'taro-block': LocalJSX.TaroBlock & JSXBase.HTMLAttributes<HTMLTaroBlockElement>;
      'taro-button': LocalJSX.TaroButton & JSXBase.HTMLAttributes<HTMLTaroButtonElement>;
      'taro-camera': LocalJSX.TaroCamera & JSXBase.HTMLAttributes<HTMLTaroCameraElement>;
      'taro-canvas': LocalJSX.TaroCanvas & JSXBase.HTMLAttributes<HTMLTaroCanvasElement>;
      'taro-checkbox': LocalJSX.TaroCheckbox & JSXBase.HTMLAttributes<HTMLTaroCheckboxElement>;
      'taro-checkbox-group': LocalJSX.TaroCheckboxGroup & JSXBase.HTMLAttributes<HTMLTaroCheckboxGroupElement>;
      'taro-cover-image': LocalJSX.TaroCoverImage & JSXBase.HTMLAttributes<HTMLTaroCoverImageElement>;
      'taro-cover-view': LocalJSX.TaroCoverView & JSXBase.HTMLAttributes<HTMLTaroCoverViewElement>;
      'taro-form': LocalJSX.TaroForm & JSXBase.HTMLAttributes<HTMLTaroFormElement>;
      'taro-icon': LocalJSX.TaroIcon & JSXBase.HTMLAttributes<HTMLTaroIconElement>;
      'taro-image': LocalJSX.TaroImage & JSXBase.HTMLAttributes<HTMLTaroImageElement>;
      'taro-input-core': LocalJSX.TaroInputCore & JSXBase.HTMLAttributes<HTMLTaroInputCoreElement>;
      'taro-label': LocalJSX.TaroLabel & JSXBase.HTMLAttributes<HTMLTaroLabelElement>;
      'taro-moveable-area': LocalJSX.TaroMoveableArea & JSXBase.HTMLAttributes<HTMLTaroMoveableAreaElement>;
      'taro-moveable-view': LocalJSX.TaroMoveableView & JSXBase.HTMLAttributes<HTMLTaroMoveableViewElement>;
      'taro-navigator': LocalJSX.TaroNavigator & JSXBase.HTMLAttributes<HTMLTaroNavigatorElement>;
      'taro-open-data': LocalJSX.TaroOpenData & JSXBase.HTMLAttributes<HTMLTaroOpenDataElement>;
      'taro-picker-core': LocalJSX.TaroPickerCore & JSXBase.HTMLAttributes<HTMLTaroPickerCoreElement>;
      'taro-picker-group': LocalJSX.TaroPickerGroup & JSXBase.HTMLAttributes<HTMLTaroPickerGroupElement>;
      'taro-picker-view': LocalJSX.TaroPickerView & JSXBase.HTMLAttributes<HTMLTaroPickerViewElement>;
      'taro-picker-view-column': LocalJSX.TaroPickerViewColumn & JSXBase.HTMLAttributes<HTMLTaroPickerViewColumnElement>;
      'taro-progress': LocalJSX.TaroProgress & JSXBase.HTMLAttributes<HTMLTaroProgressElement>;
      'taro-pull-to-refresh': LocalJSX.TaroPullToRefresh & JSXBase.HTMLAttributes<HTMLTaroPullToRefreshElement>;
      'taro-radio': LocalJSX.TaroRadio & JSXBase.HTMLAttributes<HTMLTaroRadioElement>;
      'taro-radio-group': LocalJSX.TaroRadioGroup & JSXBase.HTMLAttributes<HTMLTaroRadioGroupElement>;
      'taro-rich-text': LocalJSX.TaroRichText & JSXBase.HTMLAttributes<HTMLTaroRichTextElement>;
      'taro-scroll-view': LocalJSX.TaroScrollView & JSXBase.HTMLAttributes<HTMLTaroScrollViewElement>;
      'taro-slider': LocalJSX.TaroSlider & JSXBase.HTMLAttributes<HTMLTaroSliderElement>;
      'taro-swiper': LocalJSX.TaroSwiper & JSXBase.HTMLAttributes<HTMLTaroSwiperElement>;
      'taro-swiper-item': LocalJSX.TaroSwiperItem & JSXBase.HTMLAttributes<HTMLTaroSwiperItemElement>;
      'taro-switch': LocalJSX.TaroSwitch & JSXBase.HTMLAttributes<HTMLTaroSwitchElement>;
      'taro-tabbar': LocalJSX.TaroTabbar & JSXBase.HTMLAttributes<HTMLTaroTabbarElement>;
      'taro-text': LocalJSX.TaroText & JSXBase.HTMLAttributes<HTMLTaroTextElement>;
      'taro-textarea': LocalJSX.TaroTextarea & JSXBase.HTMLAttributes<HTMLTaroTextareaElement>;
      'taro-video': LocalJSX.TaroVideo & JSXBase.HTMLAttributes<HTMLTaroVideoElement>;
      'taro-video-control': LocalJSX.TaroVideoControl & JSXBase.HTMLAttributes<HTMLTaroVideoControlElement>;
      'taro-video-danmu': LocalJSX.TaroVideoDanmu & JSXBase.HTMLAttributes<HTMLTaroVideoDanmuElement>;
      'taro-view': LocalJSX.TaroView & JSXBase.HTMLAttributes<HTMLTaroViewElement>;
      'taro-web-view': LocalJSX.TaroWebView & JSXBase.HTMLAttributes<HTMLTaroWebViewElement>;
    }
  }
}


