export const READ_IMAGEVIDEO_PERMISSIONS = 'ohos.permission.READ_IMAGEVIDEO'
export const READ_MEDIA_PERMISSIONS = 'ohos.permission.READ_MEDIA'
export const WRITE_MEDIA_PERMISSIONS = 'ohos.permission.WRITE_MEDIA'
export const MEDIA_LOCATION_PERMISSIONS = 'ohos.permission.MEDIA_LOCATION'

export const IMAGE_PERMISSION = [READ_IMAGEVIDEO_PERMISSIONS, READ_MEDIA_PERMISSIONS, WRITE_MEDIA_PERMISSIONS, MEDIA_LOCATION_PERMISSIONS]
