export * from '@tarojs/components/mini'
export const RtcRoom = 'rtc-room'
export const PayButton = 'pay-button'
export const ConsumeCard = 'consume-card'
export const AwemeData = 'aweme-data'
export const RateButton = 'rate-button'
export const OpenData = 'open-data'
