export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/component/index/index',
    'pages/component/cover-image/cover-image',
    'pages/component/cover-view/cover-view',
    'pages/component/view/view',
    'pages/component/scroll-view/scroll-view',
    'pages/component/swiper/swiper',
    'pages/component/text/text',
    'pages/component/icon/icon',
    'pages/component/progress/progress',
    'pages/component/button/button',
    'pages/component/checkbox/checkbox',
    'pages/component/form/form',
    'pages/component/input/input',
    'pages/component/label/label',
    'pages/component/picker/picker',
    'pages/component/picker-view/picker-view',
    'pages/component/radio/radio',
    'pages/component/switch/switch',
    'pages/component/textarea/textarea',
    'pages/component/navigator/navigator',
    'pages/component/audio/audio',
    'pages/component/camera/camera',
    'pages/component/image/image',
    'pages/component/video/video',
    'pages/component/map/map',
    'pages/component/canvas/canvas',
    'pages/component/slider/slider',
    'pages/component/grid-view/grid-view',
    'pages/component/list-view/list-view',
    'pages/component/page-container/page-container',
    'pages/component/radio-group/radio-group',
    'pages/component/checkbox-group/checkbox-group',
    'pages/component/match-media/match-media',
    'pages/component/movable-view/movable-view',
    'pages/component/sticky-header/sticky-header',
    'pages/component/root-portal/root-portal',
    'pages/api/index/index',
    'pages/api/advertising/index',
    'pages/api/ai/index',
    'pages/api/alipay/index',
    'pages/api/analysis/index',
    'pages/api/basics/basics/index',
    'pages/api/basics/debug/index',
    'pages/api/basics/encryption/index',
    'pages/api/basics/miniProgram/index',
    'pages/api/basics/performance/index',
    'pages/api/basics/system/index',
    'pages/api/basics/update/index',
    'pages/api/cache/index',
    'pages/api/canvas/index',
    'pages/api/cloudServices/index',
    'pages/api/device/index',
    'pages/api/file/index',
    'pages/api/forward/index',
    'pages/api/framework/index',
    // 'pages/api/interface/interaction/index',
    // 'pages/api/interface/navigationBar/index',
    // 'pages/api/interface/background/index',
    // 'pages/api/interface/tabBar/index',
    // 'pages/api/interface/font/index',
    // 'pages/api/interface/pullDownRefresh/index',
    // 'pages/api/interface/scroll/index',
    // 'pages/api/interface/animation/index',
    // 'pages/api/interface/set-Top/index',
    // 'pages/api/interface/customizedComponents/index',
    // 'pages/api/interface/menu/index',
    // 'pages/api/interface/window/index',
    'pages/api/location/index',
    'pages/api/media/index',
    // 'pages/api/network/index',
    // 'pages/api/network/request/index',
    // 'pages/api/network/download/index',
    // 'pages/api/network/upload/index',
    // 'pages/api/network/webSocket/index',
    // 'pages/api/network/mDNS/index',
    // 'pages/api/network/TCPCommunications/index',
    // 'pages/api/network/UDPCommunications/index',
    'pages/api/openAPIS/index',
    'pages/api/payment/index',
    'pages/api/qq/index',
    'pages/api/redriection/index',
    'pages/api/routing/index',
    'pages/api/swan/index',
    'pages/api/taro/index',
    'pages/api/thirdParty/index',
    'pages/api/worker/index',
    'pages/api/wxml/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
})
