export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/component/index/index',
    'pages/component/view/view',
    'pages/component/scroll-view/scroll-view',
    'pages/component/swiper/swiper',
    'pages/component/text/text',
    'pages/component/icon/icon',
    'pages/component/progress/progress',
    'pages/component/button/button',
    'pages/component/checkbox/checkbox',
    'pages/component/form/form',
    'pages/component/input/input',
    'pages/component/label/label',
    'pages/component/picker/picker',
    'pages/component/picker-view/picker-view',
    'pages/component/radio/radio',
    'pages/component/switch/switch',
    'pages/component/textarea/textarea',
    'pages/component/navigator/navigator',
    'pages/component/audio/audio',
    'pages/component/camera/camera',
    'pages/component/image/image',
    'pages/component/map/map',
    'pages/component/canvas/canvas',
    'pages/component/slider/slider',
    'pages/component/grid-view/grid-view',
    'pages/component/list-view/list-view',
    'pages/component/page-container/page-container',
    'pages/component/radio-group/radio-group',
    'pages/component/checkbox-group/checkbox-group',
    'pages/component/match-media/match-media',
    'pages/component/sticky-header/sticky-header',
    'pages/component/root-portal/root-portal',
    'pages/api/index/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
})
