export const TYPE = 'type'
export const INPUT = 'input'
export const TARGET = 'target'
export const CONFIRM = 'confirm'
export const KEY_CODE = 'keyCode'
export const TIME_STAMP = 'timeStamp'
export const CURRENT_TARGET = 'currentTarget'