# https://github.com/dependabot/dependabot-core/issues/1736
name: Dependabot
on: pull_request_target
permissions: read-all
jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with :
          ref : ${{ github.head_ref }}
      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]
      - run: |
          git add pnpm-lock.yaml
          git commit -m "build(deps-dev): update pnpm-lock.yaml"
          git push
