on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        host: [macos-13, windows-latest, ubuntu-latest]
        exclude:
          - node-version: 18.x
            host: macos-13
          - node-version: 18.x
            host: windows-latest
          - node-version: 20.x
            host: macos-13
          - node-version: 20.x
            host: windows-latest

    runs-on: ${{ matrix.host }}
    steps:
      - name: 使用 NX 缓存
        uses: actions/cache/restore@v4
        with:
          path: .nx
          key: ${{ github.ref_name }}-NX-${{ runner.os }}-${{ matrix.node-version }}-${{ github.sha }}

      - name: 更新 NX 缓存
        uses: actions/cache/save@v4
        with:
          path: .nx
          key: NX-${{ runner.os }}-${{ matrix.node-version }}