name: Build Rust Binaries for Linux, macOS and Windows

on:
  push:
    branches:
      - next
      - feat/**
  pull_request:
    branches:
      - next

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: |
              yarn build
              strip -x *.node
          - host: windows-latest
            build: yarn build
            target: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
            build: |-
              set -e &&
              yarn build --target x86_64-unknown-linux-gnu &&
              strip *.node
          - host: macos-latest
            target: aarch64-apple-darwin
            build: |
              yarn build --target aarch64-apple-darwin
              strip -x *.node
      name: stable - ${{ matrix.settings.target }}